GCC = gcc
CFLAGS =-Wall -O2
work2-2_1: work2-2_1.c
	${GCC} ${CFLAGS} -o work2-2_1 work2-2_1.c
work2-2_2: work2-2_2.c
	${GCC} ${CFLAGS} -o work2-2_2 work2-2_2.c
work3-1_1: work3-1_1.c
	${GCC} ${CFLAGS} -o work3-1_1 work3-1_1.c
work3-1_2: work3-1_2.c
	${GCC} ${CFLAGS} -o work3-1_2 work3-1_2.c
work3-2_3: work3-2_3.c
	${GCC} ${CFLAGS} -o work3-2_3 work3-2_3.c
work3-2_4: work3-2_4.c
	${GCC} ${CFLAGS} -o work3-2_4 work3-2_4.c
work3-3_1: work3-3_1.c
	${GCC} ${CFLAGS} -o work3-3_1 work3-3_1.c
work3-3_2: work3-3_2.c
	${GCC} ${CFLAGS} -o work3-3_2 work3-3_2.c
work3-4_1: work3-4_1.c
	${GCC} ${CFLAGS} -o work3-4_1 work3-4_1.c
work3-4_2: work3-4_2.c
	${GCC} ${CFLAGS} -o work3-4_2 work3-4_2.c
mylib: mylib.c
	${GCC} ${CFLAGS} -o mylib mylib.c
genrand: genrand.c
	${GCC} ${CFLAGS} -o genrand genrand.c
getdist: getdist.c
	${GCC} ${CFLAGS} -o getdist getdist.c
clean:
	rm -f *~ *.o
